#!/bin/bash
echo 'Hola que tal'
jupyter nbconvert --execute --ExecutePreprocessor.timeout=1000 'Descriptor de SSVQ.ipynb'
echo 'Hola que tal2 '
jupyter nbconvert --execute --ExecutePreprocessor.timeout=1000 'Precompilador de texto.ipynb'


cd informe
pdflatex 'Reporte general.tex' 
okular 'Reporte general.pdf'

sleep 1